CREATE TABLE IF NOT EXISTS mz_bank_schema_migrations (
  version INT UNSIGNED NOT NULL,
  name VARCHAR(96) NOT NULL,
  applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
